### ISSUE TITLE
Acceso a Versión en Desarrollo

### ISSUE THREAD

**Issue by cmonsalvec** [jorluis2695/ISII2016G3#2]
Con la finalidad de validar que lo que están desarrollando está conforme a nuestras expectativas, solicito se me conceda el acceso a su sistema en desarrollo.

**Comment by jguilindro** [comment]
Efectivamente se ha confirmado que usted no se encuentra dentro de la base de datos del sistema.

**Comment by jguilindro** [comment]
Se procederá a realizar los cambios necesarios en la base de datos.

**Comment by jguilindro** [comment]
Se realizaron los cambios necesarios, por favor verificar que tenga acceso al sistema.

**Comment by cmonsalvec** [comment]
Favor enviarme la información necesaria para verificar acceso, incluyendo user y password. Gracias

**Comment by jguilindro** [comment]
Su usuario es cmonsalvec y su password es 12345

**Comment by cmonsalvec** [comment]
Ok, gracias. Listo. Problema solucionado
